App/Areas/Admin/Controllers/RoleManagerController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using App.Common;
using App.Common.Attributes;
using App.Entities.Identity;
using App.Services.Contracts;
using App.ViewModels.DynamicAccess;
using App.ViewModels.RoleManager;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("مدیریت نقش ها")]
    public class RoleManagerController : BaseController
    {
        private readonly IApplicationRoleManager _roleManager;
        private readonly IMapper _mapper;
        private const string RoleNotFound = "نقش یافت نشد.";
        public RoleManagerController(IApplicationRoleManager roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }

        [HttpGet,DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<JsonResult> GetRoles(string search, string order, int offset, int limit, string sort)
        {
            List<RolesViewModel> roles;
            int total = _roleManager.Roles.Count();

            if (string.IsNullOrWhiteSpace(search))
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "عنوان نقش")
            {
                if (order == "asc")
                    roles = await _roleManager.GetPaginateRolesAsync(offset, limit, true, search);
                else
                    roles = await _roleManager.GetPaginateRolesAsync(offset, limit, false, search);
            }

            else
                roles = await _roleManager.GetPaginateRolesAsync(offset, limit, null, search);

            if (search != "")
                total = roles.Count();

            return Json(new { total = total, rows = roles });
        }


        [HttpGet,AjaxOnly,DisplayName("درج و ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderRole(int? roleId)
        {
            var roleViewModel = new RolesViewModel();
            if (roleId!=null)
            {
                var role = await _roleManager.FindByIdAsync(roleId.ToString());
                if (role != null)
                    roleViewModel = _mapper.Map<RolesViewModel>(role);
                else
                    ModelState.AddModelError(string.Empty, RoleNotFound);
            }
            return PartialView("_RenderRole", roleViewModel);
        }


        [HttpPost, AjaxOnly]
        public async Task<IActionResult> CreateOrUpdate(RolesViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;
                if (viewModel.Id != null)
                {
                    var role = await _roleManager.FindByIdAsync(viewModel.Id.ToString());
                    result = await _roleManager.UpdateAsync(_mapper.Map(viewModel,role));
                }

                else
                    result = await _roleManager.CreateAsync(_mapper.Map<Role>(viewModel));

                if (result.Succeeded)
                    TempData["notification"] = OperationSuccess;
                else
                    ModelState.AddErrorsFromResult(result);
            }

            return PartialView("_RenderRole", viewModel);
        }


        [HttpGet, AjaxOnly,DisplayName("حذف")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string roleId)
        {
            if (!roleId.HasValue())
                ModelState.AddModelError(string.Empty,RoleNotFound);
            else
            {
                var role = await _roleManager.FindByIdAsync(roleId.ToString());
                if (role == null)
                    ModelState.AddModelError(string.Empty,RoleNotFound);
                else
                    return PartialView("_DeleteConfirmation", role);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete"), AjaxOnly]
        public async Task<IActionResult> DeleteConfirmed(Role model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id.ToString());
            if (role == null)
                ModelState.AddModelError(string.Empty, RoleNotFound);
            else
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation",role);
                }
                else
                    ModelState.AddErrorsFromResult(result);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("DeleteGroup"), AjaxOnly,DisplayName("حذف گروهی")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ نقشی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var role = await _roleManager.FindByIdAsync(item);
                    var result = await _roleManager.DeleteAsync(role);
                }
                TempData["notification"] = "حذف گروهی نقش ها با موفقیت انجام شد..";
            }

            return PartialView("_DeleteGroup");
        }
    }
}

App/Areas/Admin/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using App.Common;
using App.Data.Contracts;
using App.Entities.Identity;
using App.Services.Contracts;
using App.ViewModels.DynamicAccess;
using App.ViewModels.UserManager;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("مدیریت کاربران")]
    public class UserManagerController : BaseController
    {
        private readonly IApplicationUserManager _userManager;
        private readonly IApplicationRoleManager _roleManager;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _env;
        private readonly IUnitOfWork _uw;
        private const string UserNotFound = "کاربر یافت نشد.";
        public UserManagerController(IApplicationUserManager userManager, IMapper mapper, IApplicationRoleManager roleManager, IWebHostEnvironment env)
        {
            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));

            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));

            _env = env;
            _env.CheckArgumentIsNull(nameof(_env));
        }

        [HttpGet,DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetUsers(string search, string order, int offset, int limit, string sort)
        {
            List<UsersViewModel> allUsers;
            int total = _userManager.Users.Count();

            if (string.IsNullOrWhiteSpace(search))
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "نام")
            {
                if (order == "asc")
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "FirstName", search);
                else
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "FirstName desc", search);
            }

            else if (sort == "نام خانوادگی")
            {
                if (order == "asc")
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "LastName", search);
                else
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "LastName desc", search);
            }

            else if (sort == "ایمیل")
            {
                if (order == "asc")
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "Email", search);
                else
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "Email desc", search);
            }

            else if (sort == "نام کاربری")
            {
                if (order == "asc")
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "UserName", search);
                else
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "UserName desc", search);
            }

            else if (sort == "تاریخ عضویت")
            {
                if (order == "asc")
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "RegisterDateTime", search);
                else
                    allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "RegisterDateTime desc", search);
            }

            else
                allUsers = await _userManager.GetPaginateUsersAsync(offset, limit, "RegisterDateTime desc", search);

            if (search != "")
                total = allUsers.Count();

            return Json(new { total = total, rows = allUsers });
        }



        [HttpGet,DisplayName("درج و ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderUser(int? userId)
        {
            var user = new UsersViewModel();
            ViewBag.Roles = _roleManager.GetAllRoles();

            if (userId != null)
            {
                user = _mapper.Map<UsersViewModel>(await _userManager.FindUserWithRolesByIdAsync((int)userId));
                user.PersianBirthDate = user.BirthDate.ConvertMiladiToShamsi("yyyy/MM/dd");
            }

            return PartialView("_RenderUser", user);
        }


        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(UsersViewModel viewModel)
        {
            ViewBag.Roles = _roleManager.GetAllRoles();
            if (viewModel.Id!=null)
            {
                ModelState.Remove("Password");
                ModelState.Remove("ConfirmPassword");
                ModelState.Remove("ImageFile");
            }
           
            if (ModelState.IsValid)
            {
                IdentityResult result=null;
                if (viewModel.ImageFile != null)
                    viewModel.Image = _userManager.CheckAvatarFileName(viewModel.ImageFile.FileName);

                viewModel.Roles= new List<UserRole> { new UserRole { RoleId = (int)viewModel.RoleId } };
                viewModel.BirthDate= viewModel.PersianBirthDate.ConvertShamsiToMiladi();
                if (viewModel.Id != null)
                {
                    var user = await _userManager.FindByIdAsync(viewModel.Id.ToString());
                    user.FirstName = viewModel.FirstName;
                    user.LastName = viewModel.LastName;
                    user.BirthDate = viewModel.BirthDate;
                    user.Email = viewModel.Email;
                    user.UserName = viewModel.UserName;
                    user.Gender = viewModel.Gender.Value;
                    user.PhoneNumber = viewModel.PhoneNumber;
                    user.Roles = viewModel.Roles;
                    user.Bio = viewModel.Bio;
                    var userRoles = await _userManager.GetRolesAsync(user);

                    if (viewModel.ImageFile != null)
                    {
                        await viewModel.ImageFile.UploadFileAsync($"{_env.WebRootPath}/avatars/{viewModel.Image}");
                        FileExtensions.DeleteFile($"{_env.WebRootPath}/avatars/{user.Image}");
                        user.Image = viewModel.Image;
                    }

                    result = await _userManager.RemoveFromRolesAsync(user, userRoles);
                    if (result.Succeeded)
                        result = await _userManager.UpdateAsync(user);
                }

                else
                {
                    await viewModel.ImageFile.UploadFileAsync($"{_env.WebRootPath}/avatars/{viewModel.Image}");
                    viewModel.EmailConfirmed = true;
                    result = await _userManager.CreateAsync(_mapper.Map<User>(viewModel),viewModel.Password);
                }

                if (result.Succeeded)
                    TempData["notification"] = OperationSuccess;
                else
                    ModelState.AddErrorsFromResult(result);
            }

            return PartialView("_RenderUser", viewModel);
        }


        [HttpGet,DisplayName("حذف")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string userId)
        {
            if (!userId.HasValue())
                ModelState.AddModelError(string.Empty,UserNotFound);
            else
            {
                var user = await _userManager.FindByIdAsync(userId.ToString());
                if (user == null)
                    ModelState.AddModelError(string.Empty,UserNotFound);
                else
                    return PartialView("_DeleteConfirmation", user);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(User model)
        {
            var user = await _userManager.FindByIdAsync(model.Id.ToString());
            if (user == null)
                ModelState.AddModelError(string.Empty, UserNotFound);
            else
            {
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    FileExtensions.DeleteFile($"{_env.WebRootPath}/avatars/{user.Image}");
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation",user);
                }
                else
                    ModelState.AddErrorsFromResult(result);
            }

            return PartialView("_DeleteConfirmation");
        }



        [HttpPost, ActionName("DeleteGroup"),DisplayName("حذف گروهی")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ کاربری برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var user = await _userManager.FindByIdAsync(item);
                    var result = await _userManager.DeleteAsync(user);
                    FileExtensions.DeleteFile($"{_env.WebRootPath}/avatars/{user.Image}");
                }

App/Areas/Admin/Views/UserManager/Index.cshtml

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html">مدیریت کاربران</a>
            </li>

        </ul>

        <!-- User -->
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<!-- Header -->
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
</div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                مدیریت کاربران
              
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="UserManager">
                    @await Html.PartialAsync("_UserTable")
                </form>
            </div>
        </div>
    </div>
</div>




App/Areas/Admin/Views/UserManager/ResetPassword.cshtml
@model App.ViewModels.UserManager.ResetPasswordViewModel
@{
    ViewData["Title"] = "ResetPassword";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="#">بازنشانی کلمه عبور</a>
            </li>

        </ul>

        <!-- User -->
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<!-- Header -->
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
</div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                بازنشانی کلمه عبور
            </div>
            <div class="card-body">
                <form asp-action="ResetPassword" method="post">
                    <div class="card-body">
                        @if (ViewBag.AlertSuccess != null)
                        {
                            <div class="alert alert-success alert-dismissable mb-4">
                                @ViewBag.AlertSuccess
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                        <div class="row">
                            <div class="col-md-6 border-left">
                                <div asp-validation-summary="ModelOnly" class="alert alert-danger">

                                </div>
                                <div class="row">
                                    <input type="hidden" asp-for="userId" />

                                    <div class="form-group col-md-12">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control" disabled />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label asp-for="NewPassword"></label>
                                        <input asp-for="NewPassword" class="form-control" type="password" />
                                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-primary float-left">بازنشانی</button>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="alert p-0">
                                    <ul>
                                        <li>"کلمه عبور باید حداقل شامل یک کاراکتر عدد ('0'-'9') باشد."</li>
                                        <li>"کلمه عبور باید حداقل شامل یکی از کاراکترهای حرفی ('a'-'z') باشد."</li>
                                        <li>"کلمه عبور باید حداقل شامل یک حرف بزرگ ('A'-'Z') باشد."</li>
                                        <li>"کلمه عبور باید حداقل شامل 6 کاراکتر باشد." </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>






App/Areas/Admin/Views/UserManager/_DeleteConfirmation.cshtml
@model  App.Entities.Identity.User

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="modal-title">حذف اطلاعات</h3>
                    <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body clearfix">
                    @if (Model==null)
                    {
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    }
                    else
                    {
                        <h4>آیا شما می خواهید  @Model.FirstName  @Model.LastName را از لیست کاربران حذف کنید ؟</h4>
                        <form asp-action="Delete">
                            <input name="IsValid" type="hidden" value="True" />
                            <input type="hidden" asp-for="Id"/>
                        </form>
                    }
                </div>

                <div class="modal-footer">
                    @if (Model != null)
                    {
                        <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                            بله
                        </button>
                    }
                    <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                        @(Model != null ? "خیر" : "بستن")
                    </button>

                </div>
            </div>
        </div>
</div>

App/Areas/Admin/Views/UserManager/_UserTable.cshtml
@using App.Services.Contracts
@inject ISecurityTrimmingService securityTrimmingService

<div id="toolbar">
    <security-trimming asp-action="Index" asp-controller="RoleManager" asp-area="Admin">
        <a type="button" class="btn btn-primary" asp-action="Index" asp-controller="RoleManager">
            <i class="fa fa-user"></i> | مدیریت نقش ها
        </a>
    </security-trimming>
    <button type="button" class="btn btn-success" data-toggle="ajax-modal" data-url="@Url.Action("RenderUser","UserManager")">
        <i class="fa fa-plus"></i> | افزودن کاربر جدید
    </button>
    <button type="button" class="btn btn-danger" data-toggle="ajax-modal" data-url="@Url.Action("DeleteGroup","UserManager")">
        <i class="fa fa-trash"></i> | حذف گروهی
    </button>
</div>

<table id="table"
       data-toolbar="#toolbar"
       data-search="true"
       data-show-refresh="true"
       data-show-toggle="true"
       data-show-fullscreen="true"
       data-show-columns="true"
       data-detail-view="true"
       data-show-export="true"
       data-click-to-select="true"
       data-detail-formatter="detailFormatter"
       data-minimum-count-columns="2"
       data-show-pagination-switch="true"
       data-pagination="true"
       data-id-field="id"
       data-page-list="[10, 25, 50, 100, all]"
       data-show-footer="true"
       data-side-pagination="server"
       data-url="/Admin/UserManager/GetUsers"
       data-response-handler="responseHandler"></table>


<script>
        var $table = $('#table')
        var selections = []


  function get_query_params(p) {
    return {
        extraParam: 'abc',
        search: p.title,
        sort: p.sort,
        order: p.order,
        limit: p.limit,
        offset: p.offset
    }
}



        function responseHandler(res) {
            $.each(res.rows, function (i, row) {
                row.state = $.inArray(row.id, selections) !== -1
            })
            return res
        }

    function isActiveFormatter(value, row, index) {
    var spanClass = "badge badge-success";
    var IsActive = "فعال";
    if (!row.IsActive) {
        IsActive = "غیرفعال";
        spanClass = "badge badge-danger";
    }

    return [
        '<span class="' + spanClass + '">' + IsActive + '</span>'
    ].join('')
    }


    function roleFormatter(value, row, index) {
        return [
            '<span class="badge badge-primary">' + value + '</span>'
    ].join('')
  }


         function detailFormatter(index, row) {
            var html = []
            $.each(row, function (key, value) {
                if (key != "state" && key != "Id" && key!="ردیف" && key!="تصویر" && key!="IsActive")
                    html.push('<p><b>' + key + ':</b> ' + value + '</p>')

                if (key == "تصویر") {
                    var url = '@string.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)' + '/avatars/' + value;
                    html.push('<p><b>' + key + ':</b> <img src="' + url + '" height="50" />')
                }


            })
            return html.join('')
        }


      function operateFormatter(value, row, index) {
        var access = "";
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","UserManager","Details")' == 'True') {
            access = access + '<a class="btn btn btn-primary btn-sm" href=@Url.Action("Details","UserManager")?userId=' + row.Id + ' title="مدیریت"><i class="fa fa-user"></i> | مدیریت </a>';
        }
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","DynamicAccess","Index")' == 'True') {
            access = access + '<a class="btn btn btn-success mr-1 btn-sm" href=@Url.Action("Index","DynamicAccess")?userId=' + row.Id + '> سطح دسترسی </a>';
        }
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","UserManager","RenderUser")' == 'True') {
            access = access + '<button type="button" class="btn-link text-success" data-toggle="ajax-modal" data-url=@Url.Action("RenderUser", "UserManager")?userId=' + row.Id + ' title="ویرایش"><i class="fa fa-edit"></i></button >';
        }
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","UserManager","Delete")' == 'True') {
            access = access + '<button type="button" class="btn-link text-danger" data-toggle="ajax-modal" data-url=@Url.Action("Delete", "UserManager")/?userId=' + row.Id + ' title="حذف"><i class="fa fa-trash"></i></button >';
        }
        return access;
    }


     function checkBoxFormat(value, row) {
       return '<input type="checkbox" name="btSelectItem" value="' + row.Id + '" />';
    }


        function totalTextFormatter(data) {
            return 'تعداد'
        }

        function totalNameFormatter(data) {
            return data.length
        }


        function initTable() {
            $table.bootstrapTable('destroy').bootstrapTable({
                height: 600,
                locale: 'fa-IR',
                columns: [
                    [{
                        field: 'state',
                        checkbox: true,
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        formatter: checkBoxFormat
                    }, {
                        title: 'ردیف',
                        field: 'ردیف',
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        footerFormatter: totalTextFormatter
                    }, {
                        title: 'جزئیات اطلاعات کاربران',
                        colspan: 8,
                        align: 'center'
                    }],
                    [{
                        field: 'نام',
                        title: 'نام',
                        sortable: true,
                        footerFormatter: totalNameFormatter,
                        align: 'center'
                    },{
                        field: 'نام خانوادگی',
                        title: 'نام خانوادگی',
                        sortable: true,
                        align: 'center'
                    },{
                        field: 'ایمیل',
                        title: 'ایمیل',
                        sortable: true,
                        align: 'center'
                    },{
                        field: 'نام کاربری',
                        title: 'نام کاربری',
                        sortable: true,
                        align: 'center'
                    },{
                        field: 'تاریخ عضویت',
                        title: 'تاریخ عضویت',
                        sortable: true,
                        align: 'center'
                    },{
                        field: 'نقش',
                        title: 'نقش',
                        align: 'center',
                        formatter: roleFormatter
                    },{
                    field: '',
                    title: 'وضعیت',
                    align: 'center',
                    formatter: isActiveFormatter
                   },{
                        field: 'operate',
                        title: 'عملیات',
                        align: 'center',
                        events: window.operateEvents,
                        formatter: operateFormatter
                    }]
                ]
            })
        }

        $(function () {
            initTable()
            $('#locale').change(initTable)
        })</script>