App/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using App.Common;
using App.Data.Contracts;
using App.ViewModels.DynamicAccess;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("داشبورد")]
    [Authorize]
    public class DashboardController : BaseController
    {
        private readonly IUnitOfWork _uw;
        public DashboardController(IUnitOfWork uw)
        {
            _uw = uw;
        }

        //[HttpGet, DisplayName("مشاهده")]
        //[Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }
    }
}

App/Areas/Admin/Controllers/RoleManagerController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using App.Common;
using App.Common.Attributes;
using App.Entities.Identity;
using App.Services.Contracts;
using App.ViewModels.DynamicAccess;
using App.ViewModels.RoleManager;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("مدیریت نقش ها")]
    public class RoleManagerController : BaseController
    {
        private readonly IApplicationRoleManager _roleManager;
        private readonly IMapper _mapper;
        private const string RoleNotFound = "نقش یافت نشد.";
        public RoleManagerController(IApplicationRoleManager roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }

        [HttpGet,DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<JsonResult> GetRoles(string search, string order, int offset, int limit, string sort)
        {
            List<RolesViewModel> roles;
            int total = _roleManager.Roles.Count();

            if (string.IsNullOrWhiteSpace(search))
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "عنوان نقش")
            {
                if (order == "asc")
                    roles = await _roleManager.GetPaginateRolesAsync(offset, limit, true, search);
                else
                    roles = await _roleManager.GetPaginateRolesAsync(offset, limit, false, search);
            }

            else
                roles = await _roleManager.GetPaginateRolesAsync(offset, limit, null, search);

            if (search != "")
                total = roles.Count();

            return Json(new { total = total, rows = roles });
        }


        [HttpGet,AjaxOnly,DisplayName("درج و ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderRole(int? roleId)
        {
            var roleViewModel = new RolesViewModel();
            if (roleId!=null)
            {
                var role = await _roleManager.FindByIdAsync(roleId.ToString());
                if (role != null)
                    roleViewModel = _mapper.Map<RolesViewModel>(role);
                else
                    ModelState.AddModelError(string.Empty, RoleNotFound);
            }
            return PartialView("_RenderRole", roleViewModel);
        }


        [HttpPost, AjaxOnly]
        public async Task<IActionResult> CreateOrUpdate(RolesViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;
                if (viewModel.Id != null)
                {
                    var role = await _roleManager.FindByIdAsync(viewModel.Id.ToString());
                    result = await _roleManager.UpdateAsync(_mapper.Map(viewModel,role));
                }

                else
                    result = await _roleManager.CreateAsync(_mapper.Map<Role>(viewModel));

                if (result.Succeeded)
                    TempData["notification"] = OperationSuccess;
                else
                    ModelState.AddErrorsFromResult(result);
            }

            return PartialView("_RenderRole", viewModel);
        }


        [HttpGet, AjaxOnly,DisplayName("حذف")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string roleId)
        {
            if (!roleId.HasValue())
                ModelState.AddModelError(string.Empty,RoleNotFound);
            else
            {
                var role = await _roleManager.FindByIdAsync(roleId.ToString());
                if (role == null)
                    ModelState.AddModelError(string.Empty,RoleNotFound);
                else
                    return PartialView("_DeleteConfirmation", role);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete"), AjaxOnly]
        public async Task<IActionResult> DeleteConfirmed(Role model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id.ToString());
            if (role == null)
                ModelState.AddModelError(string.Empty, RoleNotFound);
            else
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation",role);
                }
                else
                    ModelState.AddErrorsFromResult(result);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("DeleteGroup"), AjaxOnly,DisplayName("حذف گروهی")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ نقشی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var role = await _roleManager.FindByIdAsync(item);
                    var result = await _roleManager.DeleteAsync(role);
                }
                TempData["notification"] = "حذف گروهی نقش ها با موفقیت انجام شد..";
            }

            return PartialView("_DeleteGroup");
        }
    }
}

App/Areas/Admin/Controllers/SiteSettingController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using App.Common;
using App.Data.Contracts;
using App.Services.Contracts;
using App.ViewModels.DynamicAccess;
using App.ViewModels.Settings;
using App.ViewModels.SiteSetting;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("تنظیمات سایت")]
    public class SiteSettingController : BaseController
    {
        private readonly IUnitOfWork _uw;
        private readonly IWritableOptions<SiteSettings> _writableLocations;
        private readonly IHostingEnvironment _env;
        public SiteSettingController(IUnitOfWork uw, IWritableOptions<SiteSettings> writableLocations, IHostingEnvironment env)
        {
            _writableLocations = writableLocations;
            _uw = uw;
            _env = env;
        }

        [HttpGet,DisplayName("مشاهده و ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            var settings = new SettingsViewModel()
            {
                Title = _writableLocations.Value.SiteInfo.Title,
                LogoName= _writableLocations.Value.SiteInfo.Logo,
                FaviconName= _writableLocations.Value.SiteInfo.Favicon,
                Description = _writableLocations.Value.SiteInfo.Description,
                MetaDescriptionTag = _writableLocations.Value.SiteInfo.MetaDescriptionTag,
                EmailHost= _writableLocations.Value.EmailSetting.Host,
                EmailUsername = _writableLocations.Value.EmailSetting.Username,
                EmailPassword = _writableLocations.Value.EmailSetting.Password,
                EmailPort = _writableLocations.Value.EmailSetting.Port,
                SenderEmail = _writableLocations.Value.EmailSetting.Email,
            };
            return View(settings);
        }

        [HttpPost]
        public async Task<IActionResult> Index(SettingsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.Favicon != null)
                {
                    viewModel.FaviconName = viewModel.Favicon.FileName;
                    await viewModel.Favicon.UploadFileAsync($"{_env.WebRootPath}/assets/img/{viewModel.FaviconName}");
                }
                else
                    viewModel.FaviconName = _writableLocations.Value.SiteInfo.Favicon;

                if (viewModel.Logo != null)
                {
                    viewModel.LogoName = viewModel.Logo.FileName;
                    await viewModel.Logo.UploadFileAsync($"{_env.WebRootPath}/assets/img/{viewModel.LogoName}");
                }
                else
                    viewModel.LogoName = _writableLocations.Value.SiteInfo.Logo;

                _writableLocations.Update(opt =>
                {
                    opt.EmailSetting.Username = viewModel.EmailUsername;
                    opt.EmailSetting.Password = viewModel.EmailPassword;
                    opt.EmailSetting.Port = viewModel.EmailPort;
                    opt.EmailSetting.Host = viewModel.EmailHost;
                    opt.EmailSetting.Email = viewModel.SenderEmail;
                    opt.SiteInfo.Title = viewModel.Title;
                    opt.SiteInfo.Description = viewModel.Description;
                    opt.SiteInfo.MetaDescriptionTag = viewModel.MetaDescriptionTag;
                    opt.SiteInfo.Logo = viewModel.LogoName;
                    opt.SiteInfo.Favicon = viewModel.FaviconName;
                });

                ViewBag.Alert = "ویرایش اطلاعات با موفقیت انجام شد.";
            }

            return View(viewModel);
        }
    }
}

App/Views/Shared/_AdminLayout.cshtml
@using App.Services.Contracts
@using App.Common
@inject IApplicationUserManager userManager

@{
    var user = await userManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title> پنل مدیریت</title>
    <!-- Favicon -->
    <link href="/assets/img/favicon.png" rel="icon" type="image/png">
    <!-- Icons -->
    <link href="/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="/assets/vendor/fontawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="/assets/css/argon.css?v=1.0.0" rel="stylesheet">
    <script src="/assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/CacheFiles/js/Ajax.js" asp-append-version="true"></script>

    <!-- Loading -->
    <link href="~/CacheFiles/lib/Loading/css/preloader.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/CacheFiles/lib/Loading/js/jquery.preloader.min.js" asp-append-version="true"></script>

    <!-- Sweetalert2 -->
    <link href="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/CacheFiles/lib/sweetalert2/dist/sweetalert2.min.js" asp-append-version="true"></script>

    <!-- DateTimePicker -->
    <link href="~/lib/bootstrap.datetimepicker/css/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
    <script src="~/lib/bootstrap.datetimepicker/js/jquery.md.bootstrap.datetimepicker.js"></script>

    <link href="~/css/bootstrap-fileinput.css" rel="stylesheet" />
    <script src="~/js/bootstrap-fileinput.min.js"></script>

    <!-- Bootstrap Table -->
    <link href="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table.js" asp-append-version="true"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/extensions/export/tableExport.js" asp-append-version="true"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/bootstrap-table-locale-all.js" asp-append-version="true"></script>
    <script src="~/CacheFiles/assets/vendor/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js" asp-append-version="true"></script>
</head>
<body>
    <!-- Sidenav -->
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Brand -->
            <a class="navbar-brand pt-0" href="./index.html">
                <img src="/assets/img/Logo.png" class="navbar-brand-img" alt="...">
                پنل مدیریت محاسب
            </a>
            <!-- User -->
            <ul class="nav align-items-center d-md-none">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                @*<img alt="Image placeholder" src="/assets/img/avatar.jpg">*@
                                @if (user.Image.HasValue())
                                {
                                    <img alt="Image placeholder" src="~/avatars/@user.Image">
                                }

                                else
                                {
                                    <img alt="Image placeholder" src="~/assets/img/UserPic.png">
                                }
                            </span>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                        <a href="./examples/profile.html" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>نمایه من</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#!" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>خروج</span>
                        </a>
                    </div>
                </li>
            </ul>
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-9 collapse-brand">
                            <a href="./index.html">
                                <img src="~/assets/img/Logo.png"> پنل مدیریت محاسب
                            </a>
                        </div>
                        <div class="col-3 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <!-- Form -->

                <hr class="my-3">
                <!-- Navigation -->
                @await Html.PartialAsync("_AdminMenu")
            </div>
        </div>
    </nav>
    <!-- Main content -->
    <div class="main-content">
        @RenderBody()
        <footer class="footer container-fluid">
            <div class="row align-items-center justify-content-xl-between">
                <div class="col-xl-6">
                    <div class="copyright text-center text-xl-left text-muted">
                        @DateTime.Now.Year  &copy;  <a href="www.Gmail.com" class="font-weight-bold ml-1" target="_blank">SadeqMozaffari@gmail.com</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="/assets/js/argon.js?v=1.0.0"></script>
    @RenderSection("Scripts", false)

</body>
</html>

App/Views/Shared/_AdminLogin.cshtml
@using App.Services.Contracts
@using App.Common
@using App.Data.Contracts
@inject IApplicationUserManager userManager

@{ 
    var user = await userManager.GetUserAsync(User);
}

<style>
.notification {
    display: inline-block;
    position: relative;
    padding: 0.2em 0.4em;
    background: #f5365c;
    border-radius: 0.2em;
    font-size: 1em;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
}
    .notification.notify::before {
    animation: ring 1.5s ease;
}
.notification::before {
    display: block;
    content: "\f086";
    font-family: "FontAwesome";
    transform-origin: top center;
}
.notification::before, .notification::after {
    color: #fff;
    text-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
}

.notification.show-count::after {
    transform: scale(1);
    opacity: 1;
}
.notification::after {
    font-family: Arial;
    font-size: 0.6em;
    font-weight: 700;
    position: absolute;
    top: -10px;
    right: -10px;
    padding: 2px 4px;
    line-height: 100%;
    border: 2px #fff solid;
    border-radius: 60px;
    background: #3498db;
    opacity: 0;
    content: attr(data-count);
    opacity: 0;
    transform: scale(0.5);
    transition: transform, opacity;
        transition-duration: 0s, 0s;
        transition-timing-function: ease, ease;
    transition-duration: 0s, 0s;
    transition-timing-function: ease, ease;
    transition-duration: 0.3s;
    transition-timing-function: ease-out;
}
.notification::before, .notification::after {
    color: #fff;
    text-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
}
</style>
<ul class="navbar-nav align-items-center d-none d-md-flex">

    <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                    @if (user.Image.HasValue())
                    {
                        <img alt="Image placeholder" src="~/avatars/@user.Image">
                    }

                    else
                    {
                        <img alt="Image placeholder" src="~/assets/img/UserPic.png">
                    }

                </span>
                <div class="media-body ml-2 d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold">@user.FirstName @user.LastName</span>
                </div>
            </div>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <a class="dropdown-item" asp-action="Profile" asp-controller="Manage" asp-route-userId="@user.Id">
                <i class="ni ni-single-02 text-primary"></i>
                <span>نمایه من</span>
            </a>
            <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Manage" asp-route-userId="@user.Id">
                <i class="ni ni-key-25 text-info"></i>
                <span>تغییر کلمه عبور</span>
            </a>
            <a class="dropdown-item" asp-action="" asp-controller="" asp-route-userId="@user.Id">
                <i class="ni ni-settings-gear-65 text-warning"></i>
                <span>احراز هویت دو مرحله </span>
            </a>
            <div class="dropdown-divider"></div>
            <form asp-action="SignOut" asp-controller="Manage" asp-area="Admin">
                <button type="submit" class="btn btn-link m-0 font-weight-normal dropdown-item">
                    <i class="ni ni-user-run text-danger"></i> خروج
                </button>
            </form>
        </div>
    </li>
</ul>

App/Views/Shared/_AdminMenu.cshtml
@using App.Common;
@addTagHelper*,NewsWebsite

<ul class="navbar-nav">
    <li class="nav-item">
        @*<security-trimming asp-action="Index" asp-controller="Dashboard" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
                <i class="ni ni-tv-2 text-primary"></i> داشبورد
            </a>
        </security-trimming>*@
    </li>


    @*<li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="RoleManager" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="RoleManager">
                <i class="fa fa-user text-pink"></i> مدیریت نقش ها
            </a>
        </security-trimming>
    </li>*@
    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="UserManager" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="UserManager">
                <i class="fa fa-users text-yellow"></i> مدیریت کاربران
            </a>
        </security-trimming> 
    </li>

    <li class="nav-item">
        <security-trimming asp-action="Index" asp-controller="SiteSetting" asp-area="Admin">
            <a class="nav-link" asp-action="Index" asp-controller="SiteSetting">
                <i class="ni ni-settings-gear-65 text-suceess"></i> تنظیمات سایت
            </a>
        </security-trimming>
    </li>
 
 
</ul>

App/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>@ViewData["Title"]</title>
    <!-- Favicon -->
    <link href="../assets/img/brand/favicon.png" rel="icon" type="image/png">
    <!-- Icons -->
    <link href="~/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="~/assets/vendor/fontawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="~/assets/css/argon.css?v=1.0.0" rel="stylesheet">
    <script src='https://www.google.com/recaptcha/api.js?hl=fa'></script>
</head>

<body class="bg-default">
    <div class="main-content">
        <!-- Navbar -->
        <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
            <div class="container px-4">
                <a class="navbar-brand" href="/Home/Index">
                    <img src="~/assets/img/Logo.png" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-collapse-main">
                    <!-- Collapse header -->
                    <div class="navbar-collapse-header d-md-none">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a href="/Home/Index">
                                    <img src="~/assets/img/Logo.png">
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                    <span></span>
                                    <span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <!-- Navbar items -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link nav-link-icon" href="../index.html">
                                <i class="fa fa-eye"></i>
                                <span class="nav-link-inner--text">مشاهده سایت</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header -->
        <div class="header bg-gradient-primary py-7 py-lg-8">

            <div class="separator separator-bottom separator-skew zindex-100">
                <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
                    <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
                </svg>
            </div>
        </div>
        <!-- Page content -->
        @RenderBody()
    </div>
    <!-- Argon Scripts -->
    <!-- Core -->
    <script src="../assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="../assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Argon JS -->
    <script src="../assets/js/argon.js?v=1.0.0"></script>
</body>

</html>

App/Views/Shared/_DeleteGroup.cshtml
<div class="modal fade" id="DeleteGroup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">حذف گروهی</h3>
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                @{var IsValid = ViewData.ModelState.IsValid.ToString();}
                <input name="IsValid" type="hidden" value="@IsValid" />
                @if (IsValid == "False")
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                }
                else
                {
                    <h4>آیا شما میخواهید موارد انتخاب شده را حذف کنید؟</h4>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-labeled  btn-danger" data-dismiss="modal">
                    @(IsValid=="True"?"خیر":"بستن")
                </button>
                @if (IsValid == "True")
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        بله
                    </button>
                }
            </div>
        </div>
    </div>
</div>

App/Views/Shared/_UserLogin.cshtml
<style>
  .btn-link {
     font-size: 13px !important;
     color: #6c6b6b;
     padding:0px !important;
     text-decoration:none !important;
  }
</style>

@if (User.Identity.IsAuthenticated)
{
    <form asp-action="SignOut" asp-controller="Account">
        <button type="submit" class="btn btn-link mr-2">
            <i class="ni ni-user-run"></i> خروج
        </button>
    </form>
    <span class="m-2">|</span>
    <a asp-action="Profile" asp-controller="Account" class="btn-link">پنل کاربری</a>
}
else
{
    <a href="#" class="login-btn" data-toggle="ajax-modal" data-url="@Url.Action("SignIn","Account")"><i class="fa fa-user" aria-hidden="true"></i></a>
}