App/Areas/Admin/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using App.Common.Attributes;

namespace App.Areas.Admin.Controllers
{
    [Area(AreaConstants.adminArea)]
    public class BaseController : Controller
    {
        public const string InsertSuccess = "درج اطلاعات با موفقیت انجام شد.";
        public const string EditSuccess = "ویرایش اطلاعات با موفقیت انجام شد.";
        public const string DeleteSuccess = "حذف اطلاعات با موفقیت انجام شد.";
        public const string OperationSuccess = "عملیات با موفقیت انجام شد.";

        public IActionResult Notification()
        {
            return Content(TempData["notification"].ToString());
        }

        [HttpGet,AjaxOnly]
        public IActionResult DeleteGroup()
        {
            return PartialView("_DeleteGroup");
        }
    }
}

App/Areas/Admin/Controllers/RoleManagerController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using App.Common;
using App.Common.Attributes;
using App.Entities.Identity;
using App.Services.Contracts;
using App.ViewModels.DynamicAccess;
using App.ViewModels.RoleManager;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("مدیریت نقش ها")]
    public class RoleManagerController : BaseController
    {
        private readonly IApplicationRoleManager _roleManager;
        private readonly IMapper _mapper;
        private const string RoleNotFound = "نقش یافت نشد.";
        public RoleManagerController(IApplicationRoleManager roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));

            _mapper = mapper;
            _mapper.CheckArgumentIsNull(nameof(_mapper));
        }

        [HttpGet,DisplayName("مشاهده")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<JsonResult> GetRoles(string search, string order, int offset, int limit, string sort)
        {
            List<RolesViewModel> roles;
            int total = _roleManager.Roles.Count();

            if (string.IsNullOrWhiteSpace(search))
                search = "";

            if (limit == 0)
                limit = total;

            if (sort == "عنوان نقش")
            {
                if (order == "asc")
                    roles = await _roleManager.GetPaginateRolesAsync(offset, limit, true, search);
                else
                    roles = await _roleManager.GetPaginateRolesAsync(offset, limit, false, search);
            }

            else
                roles = await _roleManager.GetPaginateRolesAsync(offset, limit, null, search);

            if (search != "")
                total = roles.Count();

            return Json(new { total = total, rows = roles });
        }


        [HttpGet,AjaxOnly,DisplayName("درج و ویرایش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> RenderRole(int? roleId)
        {
            var roleViewModel = new RolesViewModel();
            if (roleId!=null)
            {
                var role = await _roleManager.FindByIdAsync(roleId.ToString());
                if (role != null)
                    roleViewModel = _mapper.Map<RolesViewModel>(role);
                else
                    ModelState.AddModelError(string.Empty, RoleNotFound);
            }
            return PartialView("_RenderRole", roleViewModel);
        }


        [HttpPost, AjaxOnly]
        public async Task<IActionResult> CreateOrUpdate(RolesViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;
                if (viewModel.Id != null)
                {
                    var role = await _roleManager.FindByIdAsync(viewModel.Id.ToString());
                    result = await _roleManager.UpdateAsync(_mapper.Map(viewModel,role));
                }

                else
                    result = await _roleManager.CreateAsync(_mapper.Map<Role>(viewModel));

                if (result.Succeeded)
                    TempData["notification"] = OperationSuccess;
                else
                    ModelState.AddErrorsFromResult(result);
            }

            return PartialView("_RenderRole", viewModel);
        }


        [HttpGet, AjaxOnly,DisplayName("حذف")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Delete(string roleId)
        {
            if (!roleId.HasValue())
                ModelState.AddModelError(string.Empty,RoleNotFound);
            else
            {
                var role = await _roleManager.FindByIdAsync(roleId.ToString());
                if (role == null)
                    ModelState.AddModelError(string.Empty,RoleNotFound);
                else
                    return PartialView("_DeleteConfirmation", role);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("Delete"), AjaxOnly]
        public async Task<IActionResult> DeleteConfirmed(Role model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id.ToString());
            if (role == null)
                ModelState.AddModelError(string.Empty, RoleNotFound);
            else
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    TempData["notification"] = DeleteSuccess;
                    return PartialView("_DeleteConfirmation",role);
                }
                else
                    ModelState.AddErrorsFromResult(result);
            }
            return PartialView("_DeleteConfirmation");
        }


        [HttpPost, ActionName("DeleteGroup"), AjaxOnly,DisplayName("حذف گروهی")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> DeleteGroupConfirmed(string[] btSelectItem)
        {
            if (btSelectItem.Count() == 0)
                ModelState.AddModelError(string.Empty, "هیچ نقشی برای حذف انتخاب نشده است.");
            else
            {
                foreach (var item in btSelectItem)
                {
                    var role = await _roleManager.FindByIdAsync(item);
                    var result = await _roleManager.DeleteAsync(role);
                }
                TempData["notification"] = "حذف گروهی نقش ها با موفقیت انجام شد..";
            }

            return PartialView("_DeleteGroup");
        }
    }
}

App/Areas/Admin/Views/RoleManager/Index.cshtml

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand -->
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html">مدیریت نقش ها</a>
            </li>

        </ul>

        <!-- User -->
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<!-- Header -->
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
</div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                مدیریت نقش ها
            </div>
            <div class="card-body">
                <form asp-area="Admin" asp-controller="RoleManager">
                    @await Html.PartialAsync("_RoleTable")
                </form>
            </div>
        </div>
    </div>
</div>



App/Areas/Admin/Views/RoleManager/_DeleteConfirmation.cshtml
@model  App.Entities.Identity.Role

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="modal-title">حذف اطلاعات</h3>
                    <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body clearfix">
                    @if (Model==null)
                    {
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    }
                    else
                    {
                        <h4>آیا شما می خواهید نقش @Model.Name را حذف کنید ؟</h4>
                        <form asp-action="Delete">
                            <input name="IsValid" type="hidden" value="True" />
                            <input type="hidden" asp-for="Id"/>
                        </form>
                    }
                </div>

                <div class="modal-footer">
                    @if (Model != null)
                    {
                        <button type="submit" class="btn btn-sm btn-labeled btn-success" data-save="modal">
                            بله
                        </button>
                    }
                    <button type="button" class="btn btn-sm btn-labeled  btn-danger  mr-1" data-dismiss="modal">
                        @(Model != null ? "خیر" : "بستن")
                    </button>

                </div>
            </div>
        </div>
</div>

App/Areas/Admin/Views/RoleManager/_RenderRole.cshtml
@model App.ViewModels.RoleManager.RolesViewModel
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                @if (Model.Id != null)
                {
                    <h3 id="modal-title">ویرایش اطلاعات نقش</h3>
                }
                else
                {
                    <h3 id="modal-title">افزودن نقش جدید</h3>
                }
                <button type="button" class="close btn-link" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body clearfix">
                <form asp-action="CreateOrUpdate">
                    @if (ViewData.ModelState.IsValid.ToString() == "False")
                    {
                        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                    }

                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input type="hidden" asp-for="Id" />

                    <div class="row p-2 mt-2 mb-2">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label asp-for="Name" class="control-label"></label>
                            </div>
                            <div class="col-md-9">
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label asp-for="Description" class="control-label"></label>
                            </div>
                            <div class="col-md-9">
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">بستن</button>
                @if (Model.Id != null)
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        ذخیره تغییرات
                    </button>
                }
                else
                {
                    <button type="submit" class="btn btn-sm btn-labeled btn-success mr-1" data-save="modal">
                        افزودن اطلاعات
                    </button>
                }
            </div>
        </div>
    </div>
</div>

App/Areas/Admin/Views/RoleManager/_RoleTable.cshtml
@using App.Services.Contracts
@inject ISecurityTrimmingService securityTrimmingService

<div id="toolbar">
    <button type="button" class="btn btn-success" data-toggle="ajax-modal" data-url="@Url.Action("RenderRole","RoleManager")">
        <i class="fa fa-plus"></i> | افزودن نقش جدید
    </button>
    <button type="button" class="btn btn-danger" data-toggle="ajax-modal" data-url="@Url.Action("DeleteGroup","Base")">
        <i class="fa fa-trash"></i> | حذف گروهی
    </button>
</div>
<table id="table"
       data-toolbar="#toolbar"
       data-search="true"
       data-show-refresh="true"
       data-show-toggle="true"
       data-show-fullscreen="true"
       data-show-columns="true"
       data-detail-view="true"
       data-show-export="true"
       data-click-to-select="true"
       data-detail-formatter="detailFormatter"
       data-minimum-count-columns="2"
       data-show-pagination-switch="true"
       data-pagination="true"
       data-id-field="id"
       data-page-list="[10, 25, 50, 100, all]"
       data-show-footer="true"
       data-side-pagination="server"
       data-url="/Admin/RoleManager/GetRoles"
       data-response-handler="responseHandler"></table>


<script>
        var $table = $('#table')
        var selections = []


  function get_query_params(p) {
    return {
        extraParam: 'abc',
        search: p.title,
        sort: p.sort,
        order: p.order,
        limit: p.limit,
        offset: p.offset
    }
}


        function responseHandler(res) {
            $.each(res.rows, function (i, row) {
                row.state = $.inArray(row.id, selections) !== -1
            })
            return res
        }

         function detailFormatter(index, row) {
            var html = []
            $.each(row, function (key, value) {
                if (key != "state" && key != "Id" && key!="ردیف")
                    html.push('<p><b>' + key + ':</b> ' + value + '</p>')
            })
            return html.join('')
        }

    function operateFormatter(value, row, index) {
        var access = "";
            if ('@securityTrimmingService.CanUserAccess(User,"Admin","DynamicAccess","Role")' == 'True') {
            access = access + '<a class="btn btn btn-success mr-1 btn-sm" href=@Url.Action("Role", "DynamicAccess")?roleId=' + row.Id + '> سطح دسترسی </a>';
        }
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","RoleManager","RenderRole")' == 'True') {
            access = access + '<button type="button" class="btn-link text-success" data-toggle="ajax-modal" data-url=@Url.Action("RenderRole", "RoleManager")?roleId=' + row.Id + ' title="ویرایش"><i class="fa fa-edit"></i></button>';
        }
        if ('@securityTrimmingService.CanUserAccess(User,"Admin","RoleManager","Delete")' == 'True') {
            access = access + '<button type="button" class="btn-link text-danger" data-toggle="ajax-modal" data-url=@Url.Action("Delete", "RoleManager")/?roleId=' + row.Id + ' title="حذف"><i class="fa fa-trash"></i></button>';
        }
        return access;
    }


     function checkBoxFormat(value, row) {
       return '<input type="checkbox" name="btSelectItem" value="' + row.Id + '" />';
    }


        function totalTextFormatter(data) {
            return 'تعداد'
        }

        function totalNameFormatter(data) {
            return data.length
        }


        function initTable() {
            $table.bootstrapTable('destroy').bootstrapTable({
                height: 600,
                locale: 'fa-IR',
                columns: [
                    [{
                        field: 'state',
                        checkbox: true,
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        formatter: checkBoxFormat
                    }, {
                        title: 'ردیف',
                        field: 'ردیف',
                        rowspan: 2,
                        align: 'center',
                        valign: 'middle',
                        footerFormatter: totalTextFormatter
                    }, {
                        title: 'جزئیات اطلاعات نقش ها',
                        colspan: 3,
                        align: 'center'
                    }],
                    [{
                        field: 'عنوان نقش',
                        title: 'عنوان نقش',
                        sortable: true,
                        footerFormatter: totalNameFormatter,
                        align: 'center'
                    }, {
                        field: 'تعداد کاربران',
                        title: 'تعداد کاربران',
                        align: 'center'
                    }, {
                        field: 'operate',
                        title: 'عملیات',
                        align: 'center',
                        events: window.operateEvents,
                        formatter: operateFormatter
                    }]
                ]
            })
        }

        $(function () {
            initTable()
            $('#locale').change(initTable)
        })</script>