App/Areas/Admin/Controllers/DynamicAccessController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using App.Services.Contracts;
using App.ViewModels.DynamicAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using App.Entities.Identity;

namespace App.Areas.Admin.Controllers
{
    [DisplayName("سطح دسترسی پویا")]
    public class DynamicAccessController : BaseController
    {
        public readonly IApplicationUserManager _userManager;
        public readonly SignInManager<User> _signInManager;
       
     
        public readonly IApplicationRoleManager _roleManager;
        public readonly IMvcActionsDiscoveryService _mvcActionsDiscovery;
        public DynamicAccessController(IApplicationUserManager userManager, IMvcActionsDiscoveryService mvcActionsDiscovery, IApplicationRoleManager roleManager, SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
            _roleManager = roleManager;
            _userManager = userManager;
            _mvcActionsDiscovery = mvcActionsDiscovery;
        }


   



        [HttpGet, DisplayName("تنظیمات سطح دسترسی پویا")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Index(int userId)
        {
            if (userId == 0)
                return NotFound();


            var user = await _userManager.FindClaimsInUser(userId);
            if (user == null)
                return NotFound();

            var securedControllerActions = _mvcActionsDiscovery.GetAllSecuredControllerActionsWithPolicy(ConstantPolicies.DynamicPermission);
            return View(new DynamicAccessIndexViewModel
            {
                UserIncludeUserClaims = user,
                SecuredControllerActions = securedControllerActions,
            });
        }




        [HttpPost, ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Index(DynamicAccessIndexViewModel ViewModel)
        {
            var Result = await _userManager.AddOrUpdateClaimsAsync(ViewModel.UserId, ConstantPolicies.DynamicPermissionClaimType, ViewModel.ActionIds.Split(","));
            if (!Result.Succeeded)
                ModelState.AddModelError(string.Empty, "در حین انجام عملیات خطایی رخ داده است.");

            return RedirectToAction("Index", new { userId = ViewModel.UserId });
        }






        [HttpGet, DisplayName("تنظیمات سطح دسترسی نقش")]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        public async Task<IActionResult> Role(int RoleId)
        {
            if (RoleId == 0)
                return NotFound();


            var role = await _roleManager.FindClaimsInRole(RoleId);
            if (role == null)
                return NotFound();

            var securedControllerActions = _mvcActionsDiscovery.GetAllSecuredControllerActionsWithPolicy(ConstantPolicies.DynamicPermission);
            return View(new DynamicAccessIndexViewModel
            {
                RoleIncludeRoleClaims = role,
                SecuredControllerActions = securedControllerActions,
            });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Role(DynamicAccessIndexViewModel ViewModel)
        {
            var Result = await _roleManager.AddOrUpdateClaimsAsync(ViewModel.RoleId, ConstantPolicies.DynamicPermissionClaimType, ViewModel.ActionIds.Split(","));
            if (!Result.Succeeded)
                ModelState.AddModelError(string.Empty, "در حین انجام عملیات خطایی رخ داده است.");



            return RedirectToAction("Role", new { RoleId = ViewModel.RoleId });
        }
    }
}

App/Areas/Admin/Views/DynamicAccess/Index.cshtml
@model App.ViewModels.DynamicAccess.DynamicAccessIndexViewModel
@using App.ViewModels.DynamicAccess
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
        .jstree-node {
          font-size: 14px !important;
        }
        .jstree-default .jstree-wholerow-clicked {
           background: #fff !important;
        }
</style>

<link href="~/lib/jsTree/themes/default/style.min.css" rel="stylesheet" />
<script src="~/lib/jsTree/jstree.min.js"></script>


<div id="modal-placeholder"></div>
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
        <div class="container-fluid">
            <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
                <li>
                    <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
                </li>
                <li class="pr-2 pl-2">
                    <i class="fa fa-angle-left text-white align-middle"></i>
                </li>
                <li>
                    <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html">سطح دسترسی پویا</a>
                </li>

            </ul>
            @await Html.PartialAsync("_AdminLogin")
        </div>
    </nav>
    <div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
    </div>

<div class="container-fluid mt--7">
        <div class="row mt-5">
            <div class="card shadow w-100">
                <div class="card-header font_Vazir_Medium">
                    <h4 class="mb-1"> تنظیم سطوح دسترسی پویای کاربر «@Model.UserIncludeUserClaims.FirstName @Model.UserIncludeUserClaims.LastName»</h4>
                </div>
                <form method="post"
                      asp-controller="DynamicAccess"
                      asp-action="Index">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="card-body">
                        <input type="hidden" asp-for="ActionIds"/>
                        <input name="UserId" value="@Model.UserIncludeUserClaims.Id" type="hidden" />
                        <div id="tree">
                            <ul>
                                @{int i = 0;}
                                @foreach (var controller in Model.SecuredControllerActions.Where(x => !x.ControllerName.Contains("Api")).OrderBy(x => x.ControllerDisplayName))
                                {
                                    <li id=@("node_"+i)>
                                        @{
                                            var displayName = controller.ControllerDisplayName;
                                            if (string.IsNullOrWhiteSpace(displayName))
                                            {
                                                displayName = controller.ControllerName;
                                            }
                                        }
                                        @displayName
                                        <ul class="list-group list-group-flush pr-0">
                                            @foreach (var action in controller.MvcActions.OrderBy(x => x.ActionDisplayName))
                                            {
                                                var isSelected = Model.UserIncludeUserClaims.Claims
                                                    .Any(roleClaim => roleClaim.ClaimType == ConstantPolicies.DynamicPermissionClaimType &&
                                                                      roleClaim.ClaimValue == action.ActionId);
                                                var selected = isSelected ? "jstree-clicked" : "";
                                                var actionDisplayName = action.ActionDisplayName;
                                                if (string.IsNullOrWhiteSpace(actionDisplayName))
                                                {
                                                    actionDisplayName = $"{action}::{action.ActionId}";
                                                }

                                                <li id="@action.ActionId">
                                                    <a href="#" class="@selected"> @actionDisplayName</a>
                                                </li>

                                            }
                                        </ul>
                                    </li>
                                    i++;
                                }
                            </ul>
                        </div>
                    </div>
                    <div class="card-footer clearfix">
                        <button type="button" onclick="submitForm()" class="btn btn-primary float-left">
                            اعمال تغییرات
                            <span aria-hidden="true" class="fas fa-edit"></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


<script>
    $(function () {
        $('#tree').jstree({

            "core": {
                "themes": {
                    "icons": false
                }
            },
            "plugins": ["wholerow", "checkbox"]
        });
    });

    function submitForm() {
        var checked_ids = [];
        var selectedElms = $('#tree').jstree("get_selected", true);
        $.each(selectedElms, function () {
            if (this.id.indexOf("node") == -1)
                checked_ids.push(this.id);
        });
        $('#ActionIds').val(checked_ids.join(","));
        $( "form" ).submit();
    }
</script>

App/Areas/Admin/Views/DynamicAccess/Role.cshtml
@model App.ViewModels.DynamicAccess.DynamicAccessIndexViewModel
@using App.ViewModels.DynamicAccess
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .jstree-node {
        font-size: 14px !important;
    }

    .jstree-default .jstree-wholerow-clicked {
        background: #fff !important;
    }
</style>

<link href="~/lib/jsTree/themes/default/style.min.css" rel="stylesheet" />
<script src="~/lib/jsTree/jstree.min.js"></script>


<div id="modal-placeholder"></div>
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <ul class="nav nav-sitemap justify-content-center justify-content-xl-end">
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html"> داشبورد </a>
            </li>
            <li class="pr-2 pl-2">
                <i class="fa fa-angle-left text-white align-middle"></i>
            </li>
            <li>
                <a class="h4 mb-0 text-white d-lg-inline-block" href="./index.html">سطح دسترسی پویا</a>
            </li>

        </ul>
        @await Html.PartialAsync("_AdminLogin")
    </div>
</nav>
<div class="header bg-gradient-primary pb-4 pt-5 pt-md-8">
</div>

<div class="container-fluid mt--7">
    <div class="row mt-5">
        <div class="card shadow w-100">
            <div class="card-header font_Vazir_Medium">
                <h4 class="mb-1"> تنظیم سطوح دسترسی پویای نقش «@Model.RoleIncludeRoleClaims.Name»</h4>
            </div>
            <form method="post"
                  asp-controller="DynamicAccess"
                  asp-action="Role">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="card-body">
                    <input type="hidden" asp-for="ActionIds" />
                    <input name="RoleId" value="@Model.RoleIncludeRoleClaims.Id" type="hidden" />
                    <div id="tree">
                        <ul>
                            @{int i = 0;}
                            @foreach (var controller in Model.SecuredControllerActions.Where(x => !x.ControllerName.Contains("Api")).OrderBy(x => x.ControllerDisplayName))
                            {
                                <li id=@("node_"+i)>
                                    @{
                                        var displayName = controller.ControllerDisplayName;
                                        if (string.IsNullOrWhiteSpace(displayName))
                                        {
                                            displayName = controller.ControllerName;
                                        }
                                    }
                                    @displayName
                                    <ul class="list-group list-group-flush pr-0">
                                        @foreach (var action in controller.MvcActions.OrderBy(x => x.ActionDisplayName))
                                        {
                                            var isSelected = Model.RoleIncludeRoleClaims.Claims
                                                .Any(roleClaim => roleClaim.ClaimType == ConstantPolicies.DynamicPermissionClaimType &&
                                                                  roleClaim.ClaimValue == action.ActionId);
                                            var selected = isSelected ? "jstree-clicked" : "";
                                            var actionDisplayName = action.ActionDisplayName;
                                            if (string.IsNullOrWhiteSpace(actionDisplayName))
                                            {
                                                actionDisplayName = $"{action}::{action.ActionId}";
                                            }

                                            <li id="@action.ActionId">
                                                <a href="#" class="@selected"> @actionDisplayName</a>
                                            </li>

                                        }
                                    </ul>
                                </li>
                                i++;
                            }
                        </ul>
                    </div>
                </div>
                <div class="card-footer clearfix">
                    <button type="button" onclick="submitForm()" class="btn btn-primary float-left">
                        اعمال تغییرات
                        <span aria-hidden="true" class="fas fa-edit"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    $(function () {
        $('#tree').jstree({

            "core": {
                "themes": {
                    "icons": false
                }
            },
            "plugins": ["wholerow", "checkbox"]
        });
    });

    function submitForm() {
        var checked_ids = [];
        var selectedElms = $('#tree').jstree("get_selected", true);
        $.each(selectedElms, function () {
            if (this.id.indexOf("node") == -1)
                checked_ids.push(this.id);
        });
        $('#ActionIds').val(checked_ids.join(","));
        $( "form" ).submit();
    }
</script>